# Use official Python image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend code
COPY . .

# Collect static files
RUN python manage.py collectstatic --noinput

# Run the Gunicorn server
CMD ["python", "manage.py", "runserver",  "0.0.0.0:8000"]
